# Generated by Django 4.1 on 2022-09-22 11:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('quantity', models.IntegerField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('barcode', models.CharField(blank=True, max_length=10)),
                ('expire_date', models.DateTimeField(null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('pin', models.CharField(blank=True, max_length=4)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activated'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=15)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Card_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('transaction_balance', models.DecimalField(blank=True, decimal_places=3, max_digits=5)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.card')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
