# Generated by Django 3.2 on 2022-09-01 01:36

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('barcode', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expire_date', models.DateTimeField()),
                ('wish_message', models.CharField(max_length=70, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('pin', models.CharField(max_length=4)),
                ('status', models.CharField(choices=[('ACTIVATE', 'Activated'), ('INACTIVE', 'Inactive')], default='INACTIVE', max_length=15)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('transaction_created_at', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('transaction_updated_at', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('transaction_balance', models.DecimalField(decimal_places=3, max_digits=5)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.card')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.address')),
            ],
        ),
        migrations.CreateModel(
            name='Card_Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='card_design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.card_design'),
        ),
        migrations.AddField(
            model_name='card',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giftcard.customer'),
        ),
        migrations.AddField(
            model_name='card',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant'),
        ),
    ]
