# Generated by Django 4.1 on 2022-09-25 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_balance',
            new_name='deducted_balance',
        ),
    ]
