# Generated by Django 3.2 on 2022-09-28 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
        ('giftcard', '0005_alter_card_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_design',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='merchants.merchant'),
        ),
    ]
