# Generated by Django 3.2 on 2022-09-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giftcard', '0007_alter_card_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_design',
            name='logo',
            field=models.ImageField(null=True, upload_to='designs'),
        ),
    ]
